apiVersion: v1
kind: Template
objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: "${APPLICATION_NAME}-env"
    data:
      APP_KEY: "base64:Kc3A72E+ROSkaO7KmAxKAAgdox1a8BBVOpeRgWdwitw="
      APP_ENV: "testing"
      APP_DEBUG: "true"
      APP_TIMEZONE: "Asia/Tehran"
      APP_LOCALE: "fa"
      LOG_LEVEL: "debug"
      CACHE_DRIVER: "file"

      DB_CONNECTION: "mysql"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_DATABASE: "${DB_DATABASE}"

      RABBITMQ_HOST: "${RABBITMQ_HOST}"
      RABBITMQ_PORT: "${RABBITMQ_PORT}"
      RABBITMQ_NOTIFICATION_QUEUE: "${RABBITMQ_NOTIFICATION_QUEUE}"

      APP_URL: "https://snapp-hr-test-env.apps.private.teh-1.snappcloud.io"
      LOG_CHANNEL: stack

      BROADCAST_DRIVER: "log"
      SESSION_DRIVER: "file"
      SESSION_LIFETIME: "120"
      JWT_SECRET: "tAL7Kcl1UnareF2hXHzadzSnLATVvtPLANxXrkDQZ83jwnQ8T5mmnfZwVrnYmLZe"
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: "${APPLICATION_NAME}-rr"
    data:
      roundrunner.yaml: |-
        http:
          address: :${RR_PORT}
          workers:
            command: "php psr-worker.php"
            pool:
              numWorkers: 1
        rpc:
          enable: false
parameters:
  - name: APPLICATION_NAME
    value: "snapp-hr"
    required: true

  - name: DB_HOST
    value: "mysql"
    required: true

  - name: DB_PORT
    value: "3306"
    required: true

  - name: DB_DATABASE
    value: "snapp_hr"
    required: true

  - name: RR_PORT
    value: "8080"
    required: true

  - name: RABBITMQ_HOST
    value: "rabbitmq"
    required: true

  - name: RABBITMQ_PORT
    value: "5672"
    required: true

  - name: RABBITMQ_NOTIFICATION_QUEUE
    value: "notification"
    required: true
