apiVersion: v1
kind: Template
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        application: ${APPLICATION_NAME}
        app: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}
    spec:
      replicas: 1
      selector:
        application: ${APPLICATION_NAME}
        deploymentconfig: ${APPLICATION_NAME}
      strategy:
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            application: ${APPLICATION_NAME}
            app: ${APPLICATION_NAME}
            deploymentconfig: ${APPLICATION_NAME}
        spec:
          containers:
            - name: roadrunner
              image: "${REGISTRY_URI}/${PROJECT_NAME}/${APPLICATION_NAME}-roadrunner:${IMAGE_TAG}"
              imagePullPolicy: Always
              resources:
                limits:
                  memory: 512Mi
              env:
                - name: DB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: mysql
                      key: database-user
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mysql
                      key: database-password
                - name: RABBITMQ_USER
                  valueFrom:
                    secretKeyRef:
                      name: rabbitmq
                      key: rabbitmq-user
                - name: RABBITMQ_PASS
                  valueFrom:
                    secretKeyRef:
                      name: rabbitmq
                      key: rabbitmq-password
                - name: EMQ_SUPER_USER
                  valueFrom:
                    secretKeyRef:
                      name: ${APPLICATION_NAME}-emq
                      key: emq-super-user
                - name: EMQ_SUPER_PASS
                  valueFrom:
                    secretKeyRef:
                      name: ${APPLICATION_NAME}-emq
                      key: emq-super-pass
              envFrom:
                - configMapRef:
                    name: "${APPLICATION_NAME}-env"
              ports:
                - containerPort: 8080
                  protocol: TCP
              volumeMounts:
                - name: "${APPLICATION_NAME}-rr"
                  mountPath: "/app/.rr.yaml"
                  subPath: roundrunner.yaml
          volumes:
            - name: "${APPLICATION_NAME}-rr"
              configMap:
                name: "${APPLICATION_NAME}-rr"
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
    triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
            - snapp-hr-roadrunner
          from:
            kind: ImageStreamTag
            name: 'snapp-hr-roadrunner:master'
            namespace: test-env
        type: ImageChange
parameters:
  - name: APPLICATION_NAME
    value: "snapp-hr"
    required: true

  - name: IMAGE_TAG
    displayName: Docker image tag
    value: master
    required: true

  - name: REGISTRY_URI
    displayName: Cloud Docker Registry base url
    value: docker-registry.default.svc:5000
    required: true

  - name: PROJECT_NAME
    value: test-env
    required: true
