apiVersion: v1
kind: Template
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        application: ${APPLICATION_NAME}
        app: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}
    spec:
      replicas: 1
      selector:
        application: ${APPLICATION_NAME}
        deploymentconfig: ${APPLICATION_NAME}
      strategy:
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            application: ${APPLICATION_NAME}
            app: ${APPLICATION_NAME}
            deploymentconfig: ${APPLICATION_NAME}
        spec:
          containers:
            - name: roadrunner
              image: "${REGISTRY_URI}/${PROJECT_NAME}/${APPLICATION_NAME}-rr:${IMAGE_TAG}"
              imagePullPolicy: Always
              resources:
                limits:
                  memory: 512Mi
              envFrom:
                - configMapRef:
                    name: "${APPLICATION_NAME}-env"
              ports:
                - containerPort: 8080
                  protocol: TCP
              volumeMounts:
                - name: "${APPLICATION_NAME}-config"
                  mountPath: "/app/.rr.yaml"
                  subPath: roundrunner.yaml
          volumes:
            - name: "${APPLICATION_NAME}-config"
              configMap:
                name: "${APPLICATION_NAME}"
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
    triggers: []
parameters:
  - name: APPLICATION_NAME
    value: "snapp-hr"
    required: true

  - name: IMAGE_TAG
    displayName: Docker image tag
    value: master
    required: true

  - name: REGISTRY_URI
    displayName: Cloud Docker Registry base url
    value: docker-registry.default.svc:5000
    required: true

  - name: PROJECT_NAME
    value: modares-test-env
    required: true
