apiVersion: v1
kind: Template
objects:
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        application: ${APPLICATION_NAME}
        app: ${APPLICATION_NAME}
        environment: ${APP_ENVIRONMENT}
        router: public
      name: ${APPLICATION_NAME}
    spec:
      port:
        targetPort: ${PORT}-tcp
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
      to:
        kind: Service
        name: ${APPLICATION_NAME}
        weight: 100
      wildcardPolicy: None

parameters:
  - name: PORT
    value: "8080"
    required: true

  - name: APPLICATION_NAME
    value: "snapp-hr"
    required: true


  - name: APP_ENVIRONMENT
    value: "testing"
    required: true
