apiVersion: v1
kind: Template
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: "${APPLICATION_NAME}-emq"
    labels:
      app: ${APPLICATION_NAME}
  stringData:
    emq-super-user: "${EMQ_SUPER_USER}"
    emq-super-pass: "${EMQ_SUPER_PASS}"
parameters:
  - name: APPLICATION_NAME
    displayName: Application Name
    required: true
    value: "snapp-hr"
  - name: EMQ_SUPER_USER
    displayName: Pusher Key
    required: true
    value: "superman"
  - name: EMQ_SUPER_PASS
    displayName: Pusher Secret
    required: true
    value: "superpass"
