apiVersion: v1
kind: Template
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
      labels:
        application: "${APPLICATION_NAME}"
        app: "${APPLICATION_NAME}"
      name: "${APPLICATION_NAME}"
    spec:
      ports:
        - name: "${PORT}-tcp"
          port: ${{PORT}}
          protocol: TCP
          targetPort: ${{PORT}}
      selector:
        application: "${APPLICATION_NAME}"
        deploymentconfig: "${APPLICATION_NAME}"
      sessionAffinity: None  
parameters:
  - name: PORT
    value: "8080"
    required: true

  - name: APPLICATION_NAME
    value: "snapp-hr"
    required: true
