version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    image: snapp-hr_app
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network
    links:
      - db
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: snapp_hr
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: mysql13243546
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network
# in development env only.
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8000:80"
    environment:
      MYSQL_DATABASE: snapp_hr
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    networks:
      - app-network
  rabbit_node:
    container_name: rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE='secret_cookie'
    networks:
      - app-network
    hostname: rabbit_node
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    tty: true
    volumes:
      - rabbit:/var/lib/rabbitmq
      - ./docker/rabbitmq/conf/:/etc/rabbitmq/
    command:  bash -c "sleep 10; rabbitmq-server;"
volumes:
  rabbit:
    driver: local
networks:
  app-network:
    driver: bridge